[project]
name = "Labeling"
authors = [
  {name = "Aleksei Sukharev", email = "galsrv@gmail.com"},
]
version = "0.5.0"
description = "Products labeling application"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["label", "printer", "barcode", "scales", "packaging"]
dependencies = [
    "alembic>=1.18.4",
    "alembic-postgresql-enum>=1.10.0",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.136.1",
    "loguru>=0.7.3",
    "pillow>=12.2.0",
    "pyjwt>=2.12.1",
    "sqlalchemy>=2.0.49",
]

[tool.ruff]
# Core settings
target-version = "py312"
line-length = 200
indent-width = 4
preview = true
exclude = ["alembic", ".venv", "__pycache__"]

[tool.ruff.lint]
# Choose which rule families to check
select = [
    "E", "F", "W", "I", "N", "D", "D400", "C90", "A", "ANN",
    "ASYNC", "COM", "RET"
]
# Ignore selected rules
ignore = [
    "D100",    # Missing docstring in public module
    "RET504",  # unnecessary variable assignment before return
    "D107",    # Missing docstring in `__init__`
    "A003",    # Ignore shadowind system vars like 'id'
    "ANN002",  # Missing type annotation for `*args`
    "ANN003",  # Missing type annotation for `**kwargs`
    # "I001",    # Ignore imports sorting
    # "COM812",  # Trailing comma missing
]

# Per-file ignores
[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = [
    "E401",   # multiple-imports-on-one-line
    "E402"    # module-import-not-at-top-of-file
]

# Optional: limit complexity
[tool.ruff.lint.mccabe]
max-complexity = 10

# Allow star-args without explicit type annotation
[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true

# Prefer single quotes
[tool.ruff.format]
quote-style = "single"
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = 80

# Sorting imports
[tool.ruff.lint.isort]
case-sensitive = true

# Optional: documentation style
[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyright]
typeCheckingMode = "off"
reportAttributeAccessIssue = false
reportReturnType = false
reportArgumentType = false
reportOptionalMemberAccess = false
