"""Drivers table deleted

Revision ID: 2f39f7592a02
Revises: f99e9bf01e73
Create Date: 2026-02-11 20:23:01.136438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from device_drivers.drivers import scales_drivers
from device_drivers.drivers import printer_drivers

# revision identifiers, used by Alembic.
revision: str = '2f39f7592a02'
down_revision: Union[str, Sequence[str], None] = 'f99e9bf01e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_templates', sa.Column('driver_name', sa.String(length=20), server_default='dpl', nullable=False))
    op.create_check_constraint(
        "check_driver_name_valid",
        "label_templates",
        f"driver_name IN ({', '.join(repr(v) for v in printer_drivers.keys())})",
    )
    op.drop_constraint(op.f('label_templates_driver_id_fkey'), 'label_templates', type_='foreignkey')
    op.drop_column('label_templates', 'driver_id')
    op.add_column('printers', sa.Column('driver_name', sa.String(length=20), server_default='dpl', nullable=False))
    op.create_check_constraint(
        "check_driver_name_valid",
        "printers",
        f"driver_name IN ({', '.join(repr(v) for v in printer_drivers.keys())})",
    )
    op.drop_constraint(op.f('printers_driver_id_fkey'), 'printers', type_='foreignkey')
    op.drop_column('printers', 'driver_id')
    op.add_column('scales', sa.Column('driver_name', sa.String(length=20), server_default='tenzo_m', nullable=False))
    op.create_check_constraint(
        "check_driver_name_valid",
        "scales",
        f"driver_name IN ({', '.join(repr(v) for v in scales_drivers.keys())})",
    )
    op.drop_constraint(op.f('scales_driver_id_fkey'), 'scales', type_='foreignkey')
    op.drop_column('scales', 'driver_id')
    op.drop_table('drivers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scales', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('scales_driver_id_fkey'), 'scales', 'drivers', ['driver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scales', 'driver_name')
    op.add_column('printers', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('printers_driver_id_fkey'), 'printers', 'drivers', ['driver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('printers', 'driver_name')
    op.add_column('label_templates', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('label_templates_driver_id_fkey'), 'label_templates', 'drivers', ['driver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('label_templates', 'driver_name')
    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('PRINTER', 'SCALES', name='device_driver_enum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('drivers_pkey')),
    sa.UniqueConstraint('name', name=op.f('drivers_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
