"""tare weight field name change

Revision ID: 412c359a6601
Revises: f7f301cd8423
Create Date: 2025-11-22 15:45:32.124511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412c359a6601'
down_revision: Union[str, Sequence[str], None] = 'f7f301cd8423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tare_weight', sa.Float(), nullable=False))
    op.drop_column('items', 'package_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('package_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('items', 'tare_weight')
    # ### end Alembic commands ###
