"""SGTIN v5

Revision ID: a33da517c67c
Revises: d4917a9abb2e
Create Date: 2026-04-05 18:15:36.695741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33da517c67c'
down_revision: Union[str, Sequence[str], None] = 'd4917a9abb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('production_date_range', 'orders', type_='check')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
