"""users_model

Revision ID: a71c8000fff1
Revises: a33da517c67c
Create Date: 2026-04-20 20:50:08.661345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71c8000fff1'
down_revision: Union[str, Sequence[str], None] = 'a33da517c67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('is_items_view_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_items_edit_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_labels_view_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_labels_edit_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_orders_view_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_orders_edit_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_printers_view_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_printers_edit_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_scales_view_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_scales_edit_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_sgtins_view_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_sgtins_edit_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_users_view_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_users_edit_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_workplaces_view_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_workplaces_edit_permitted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='unique_role_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('first_name', sa.String(length=15), nullable=False),
    sa.Column('last_name', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='unique_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
