"""SGTIN v3

Revision ID: b8cd6cfd3e3a
Revises: 97fa17869836
Create Date: 2026-04-04 22:35:32.334147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cd6cfd3e3a'
down_revision: Union[str, Sequence[str], None] = '97fa17869836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgtins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gtin', sa.String(length=14), nullable=False),
    sa.Column('sgtin', sa.String(length=6), nullable=False),
    sa.Column('crypto_end', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'PRINTED', 'EXPIRED', name='sgtin_status_enum'), server_default=sa.text("'ISSUED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('shelf_life', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('expired_at', sa.DateTime(), sa.Computed("created_at + shelf_life * INTERVAL '1 day'", persisted=True), nullable=False),
    sa.CheckConstraint('length(crypto_end) = 4', name='crypto_end_length'),
    sa.CheckConstraint('length(gtin) = 14', name='gtin_length'),
    sa.CheckConstraint('length(sgtin) = 6', name='sgtin_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sgtin', 'crypto_end', name='unique_sgtin_crypto_end')
    )
    op.create_index('ix_sgtins_gtin', 'sgtins', ['gtin'], unique=False)
    op.create_index('ix_sgtins_gtin_status', 'sgtins', ['gtin', 'status'], unique=False)
    op.drop_index(op.f('ix_items_gtin'), table_name='items')
    op.create_unique_constraint('unique_items_gtin', 'items', ['gtin'])
    op.alter_column('label_templates', 'driver_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'dpl'::character varying"))
    op.alter_column('printers', 'driver_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'dpl'::character varying"))
    op.alter_column('scales', 'driver_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'tenzo_m'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scales', 'driver_name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'tenzo_m'::character varying"))
    op.alter_column('printers', 'driver_name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'dpl'::character varying"))
    op.alter_column('label_templates', 'driver_name',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'dpl'::character varying"))
    op.drop_constraint('unique_items_gtin', 'items', type_='unique')
    op.create_index(op.f('ix_items_gtin'), 'items', ['gtin'], unique=False)
    op.drop_index('ix_sgtins_gtin_status', table_name='sgtins')
    op.drop_index('ix_sgtins_gtin', table_name='sgtins')
    op.drop_table('sgtins')
    # ### end Alembic commands ###
