"""SGTIN v4

Revision ID: d4917a9abb2e
Revises: b8cd6cfd3e3a
Create Date: 2026-04-05 17:18:28.997762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4917a9abb2e'
down_revision: Union[str, Sequence[str], None] = 'b8cd6cfd3e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgtins', sa.Column('printed_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sgtins', 'printed_at')
    # ### end Alembic commands ###
