"""initial

Revision ID: fba584f8be87
Revises: 
Create Date: 2025-11-08 16:11:07.835305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fba584f8be87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ingredients', sa.String(length=255), nullable=False),
    sa.Column('nutrition', sa.String(length=255), nullable=False),
    sa.Column('fixed_weight', sa.Boolean(), nullable=False),
    sa.Column('nominal_weight', sa.Float(), nullable=False),
    sa.Column('min_weight', sa.Float(), nullable=False),
    sa.Column('max_weight', sa.Float(), nullable=False),
    sa.Column('package_weight', sa.Float(), nullable=False),
    sa.Column('gtin', sa.BigInteger(), nullable=False),
    sa.Column('shelf_life', sa.Integer(), nullable=False),
    sa.Column('units_per_box', sa.Integer(), nullable=False),
    sa.CheckConstraint('gtin <= 9999999999999', name='check_gtin_max'),
    sa.CheckConstraint('units_per_box >= 1', name='check_units_per_box_min'),
    sa.CheckConstraint('gtin >= 1000000000000', name='check_gtin_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_gtin'), 'items', ['gtin'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('driver', sa.Enum('TENZO_M', name='scales_driver_enum'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.CheckConstraint('port <= 65535', name='check_port_max'),
    sa.CheckConstraint('port >= 1024', name='check_port_min'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scales_ip'), 'scales', ['ip'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVE', 'CLOSED', name='order_status_enum'), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('produced_kg', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('produced_boxes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("production_date >= CURRENT_DATE - INTERVAL '1 day' AND production_date <= CURRENT_DATE + INTERVAL '30 day'", name='production_date_range'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('scales_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scales_id'], ['scales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workplaces')
    op.drop_table('orders')
    op.drop_index(op.f('ix_scales_ip'), table_name='scales')
    op.drop_table('scales')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_gtin'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
