"""ordered_kg field added

Revision ID: 1f0f039dd676
Revises: 412c359a6601
Create Date: 2025-11-22 15:54:39.101462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0f039dd676'
down_revision: Union[str, Sequence[str], None] = '412c359a6601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ordered_kg', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('ordered_boxes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ordered_boxes')
    op.drop_column('orders', 'ordered_kg')
    # ### end Alembic commands ###
