"""Templates & Processes

Revision ID: 32b01eba76e1
Revises: 1f0f039dd676
Create Date: 2026-01-01 16:09:32.754958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32b01eba76e1'
down_revision: Union[str, Sequence[str], None] = '1f0f039dd676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('print_command', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.CheckConstraint('port <= 65535', name='check_port_max'),
    sa.CheckConstraint('port >= 1024', name='check_port_min'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printers_ip'), 'printers', ['ip'], unique=False)
    op.add_column('items', sa.Column('item_label_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'label_templates', ['item_label_template_id'], ['id'], ondelete='SET NULL')
    op.add_column('workplaces', sa.Column('printer1_id', sa.Integer(), nullable=True))
    op.add_column('workplaces', sa.Column('printer2_id', sa.Integer(), nullable=True))
    op.alter_column('workplaces', 'scales_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'workplaces', 'printers', ['printer2_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workplaces', 'printers', ['printer1_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workplaces', type_='foreignkey')
    op.drop_constraint(None, 'workplaces', type_='foreignkey')
    op.alter_column('workplaces', 'scales_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('workplaces', 'printer2_id')
    op.drop_column('workplaces', 'printer1_id')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'item_label_template_id')
    op.drop_index(op.f('ix_printers_ip'), table_name='printers')
    op.drop_table('printers')
    op.drop_table('label_templates')
    op.drop_table('processes')
    # ### end Alembic commands ###
