"""drivers model

Revision ID: f7f301cd8423
Revises: fba584f8be87
Create Date: 2025-11-22 15:20:18.607609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7f301cd8423'
down_revision: Union[str, Sequence[str], None] = 'fba584f8be87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('scales', sa.Column('driver_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'scales', 'drivers', ['driver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scales', 'driver')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scales', sa.Column('driver', postgresql.ENUM('TENZO_M', name='scales_driver_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scales', type_='foreignkey')
    op.drop_column('scales', 'driver_id')
    op.drop_table('drivers')
    # ### end Alembic commands ###
