"""driver types

Revision ID: f99e9bf01e73
Revises: 32b01eba76e1
Create Date: 2026-01-04 13:19:09.830484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f99e9bf01e73'
down_revision: Union[str, Sequence[str], None] = '32b01eba76e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    driver_enum = postgresql.ENUM("PRINTER", "SCALES", name="device_driver_enum")
    driver_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "drivers",
        sa.Column(
            "type",
            driver_enum,
            nullable=False,
            server_default="SCALES",   # important for existing rows!
        ),
    )

    # optional: drop server_default afterward so future inserts use ORM default
    op.alter_column("drivers", "type", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'type')
    # ### end Alembic commands ###
